name = "svg2png"
main = "src/index.js"
compatibility_date = "2024-09-12"
account_id = "c4181c74ba33fc8edf2d8cca0dc37bd1"
workers_dev = false

[observability]
enabled = true

[env.dev]
name = "svg2png-dev"
